# Disable the Gradle daemon for Continuous Integration servers as
#  correctness is usually a priority over speed in CI environments.
#  Using a fresh runtime for each build is more reliable since the runtime is completely
#  isolated from any previous builds.

variables:
     GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
    - cd Backend
     
stages:  
    - build
    - test

build:  
    stage: build
    script:
     - cd CanonBackEnd
     - ./gradlew assemble

test:  
    stage: test
    script:
     - cd CanonBackEnd
     - ./gradlew test


